-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone
);

-- Add columns if they don't exist (safe merge)
alter table public.profiles add column if not exists username text unique;
alter table public.profiles add column if not exists avatar_url text;

-- Safe Policy Creation (Drop first to avoid errors)
alter table public.profiles enable row level security;

do $$ begin
  drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
  drop policy if exists "Users can insert their own profile." on public.profiles;
  drop policy if exists "Users can update own profile." on public.profiles;
end $$;

create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- 2. ROOMS TABLE
create table if not exists public.rooms (
  id text primary key,
  name text not null,
  description text,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.rooms enable row level security;

do $$ begin
  drop policy if exists "Rooms are viewable by everyone." on public.rooms;
end $$;

create policy "Rooms are viewable by everyone." on rooms for select using ( true );

-- Seed default rooms (idempotent)
insert into public.rooms (id, name, description, icon)
values
  ('community-chat', 'General Chat', 'The main lobby for everyone.', 'MessageSquare'),
  ('report-issue', 'Report Issue', 'Found a bug? Let us know here.', 'AlertCircle'),
  ('tech-talk', 'Tech Talk', 'Discuss code, gadgets, and AI.', 'Cpu'),
  ('casual-corner', 'Casual Corner', 'Just chilling and vibing.', 'Coffee')
on conflict (id) do nothing;

-- 3. MESSAGES TABLE
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id text references public.rooms(id) not null,
  user_id uuid references public.profiles(id) not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.messages enable row level security;

do $$ begin
  drop policy if exists "Messages are viewable by everyone." on public.messages;
  drop policy if exists "Authenticated users can insert messages." on public.messages;
end $$;

create policy "Messages are viewable by everyone." on messages for select using ( true );
create policy "Authenticated users can insert messages." on messages for insert with check ( auth.role() = 'authenticated' or auth.role() = 'anon' );

-- 4. REALTIME SETUP
-- Add table to publication if not already added trying to match carefully
do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'messages') then
    alter publication supabase_realtime add table messages;
  end if;
end $$;
