-- PANDAA Chatbot V1.3 - Knowledge Base Schema
-- This schema supports Full Text Search (FTS) for the bubblesort_dataset.csv

-- 1. Create Knowledge Table (Run this in Supabase SQL Editor)
create table if not exists public.pandaa_knowledge (
    id bigint generated by default as identity primary key,
    instruction text not null, -- The question or trigger
    response text not null,    -- The answer
    category text,             -- Category (Recruitment, Services, etc.)
    project text,             -- Project (GKKIntern, Ghar Ka Khana)
    created_at timestamp with time zone default now()
);

-- 2. Enable RLS (Security)
alter table public.pandaa_knowledge enable row level security;
create policy "PANDAA: Anyone can read knowledge" on public.pandaa_knowledge for select using (true);

-- 3. Create Search Function (FTS)
-- This function is called by the frontend via supabase.rpc('search_pandaa_knowledge', { p_query: '...' })
create or replace function public.search_pandaa_knowledge(p_query text)
returns table (
    instruction text,
    response text,
    rank float4
) language plpgsql security definer as $$
begin
    return query
    select 
        pk.instruction,
        pk.response,
        ts_rank(
            to_tsvector('english', pk.instruction || ' ' || pk.response), 
            plainto_tsquery('english', p_query)
        ) as rank
    from public.pandaa_knowledge pk
    where 
        to_tsvector('english', pk.instruction || ' ' || pk.response) @@ plainto_tsquery('english', p_query)
        or pk.instruction ilike '%' || p_query || '%' -- Fallback for very short queries
    order by rank desc
    limit 5;
end;
$$;

-- 4. Example Data Loading (Top rows from bubblesort_dataset.csv)
insert into public.pandaa_knowledge (instruction, response, category, project) values
('How do I apply for GKKIntern right now?', 'Apply through the GKKIntern internal portal and submit the required form. The team reviews applications in active batches.', 'Recruitment', 'GKKIntern'),
('Is GKKIntern currently active?', 'Yes, GKKIntern is currently running and accepting internship-related engagement. It is an active sub-company under Bubblesort.', 'Status', 'GKKIntern'),
('What is the internship duration at GKKIntern now?', 'The current internship duration is 1 month for the running program. Exact timelines are confirmed during onboarding.', 'Duration', 'GKKIntern'),
('Who is the Founder & CEO of Bubblesort / GKK?', 'ADITYA ROUTH serves as Founder & CEO of Bubblesort. GKK (Ghar Ka Khana) is a sub-project under Bubblesort.', 'Leadership', 'Bubblesort'),
('What is GKK (Ghar Ka Khana)?', 'Ghar Ka Khana (GKK) is a Bubblesort sub-project currently in alpha testing. It focuses on home-cooked food delivery.', 'Status', 'Ghar Ka Khana'),
('Who leads technical direction for GKKIntern?', 'Technical direction is led by DEBRAJ PRADHAN, CTO. Engineering choices are aligned with project execution goals.', 'Leadership', 'GKKIntern'),
('Who handles curriculum quality in GKKIntern?', 'Curriculum direction is led by ANKAN MUKHERJEE as HOC & Executive Head. Program structure and learning quality are managed there.', 'Leadership', 'GKKIntern'),
('Who is PAYEL DEY?', 'PAYEL DEY serves as Co-Founder & CMO (Chief Management Officer) at Bubblesort.', 'Leadership', 'Bubblesort');
