-- PANDAA Chatbot V1.3 - Database Schema
-- For Supabase (PostgreSQL)

-- 1. TRACKING SESSIONS (User Profile/Limits)
create table if not exists public.pandaa_sessions (
    id uuid default uuid_generate_v4() primary key,
    token text unique not null,
    name text,
    ai_msg_count int default 0,
    refine_count int default 0,
    last_name_change timestamp with time zone default now(),
    created_at timestamp with time zone default now()
);

-- 2. CHAT MEMORY (History)
create table if not exists public.pandaa_chat_history (
    id bigint generated by default as identity primary key,
    session_id uuid references public.pandaa_sessions(id) on delete cascade not null,
    role text check (role in ('user', 'assistant')) not null,
    content text not null,
    created_at timestamp with time zone default now()
);

-- 3. CONTACT INQUIRIES (Syncing with Sheets + DB)
create table if not exists public.pandaa_inquiries (
    id uuid default uuid_generate_v4() primary key,
    session_id uuid references public.pandaa_sessions(id) on delete set null,
    name text,
    email text not null,
    message text not null,
    source text not null, -- 'MAIN', 'DASHBOARD', 'BENTO'
    status text default 'pending',
    created_at timestamp with time zone default now()
);

-- 4. RLS POLICIES (Security)
alter table public.pandaa_sessions enable row level security;
alter table public.pandaa_chat_history enable row level security;
alter table public.pandaa_inquiries enable row level security;

-- Allow anonymous access via token (frontend uses userToken)
create policy "PANDAA: Anyone can manage their own session"
    on public.pandaa_sessions for all
    using (true) with check (true);

create policy "PANDAA: Anyone can manage their own history"
    on public.pandaa_chat_history for all
    using (true) with check (true);

create policy "PANDAA: Anyone can submit inquiries"
    on public.pandaa_inquiries for insert
    with check (true);

-- 5. HELPER FUNCTION: Get Application Status
-- This will be used by the frontend to inject status into AI prompt
create or replace function public.get_pandaa_application_status(p_email text)
returns table (
    full_name text,
    status text,
    remark text,
    applied_at timestamp with time zone
) language plpgsql security definer as $$
begin
    return query
    select 
        a.full_name,
        a.status,
        a.remark,
        a.created_at as applied_at
    from public.applications a
    where a.email = p_email
    order by a.created_at desc
    limit 1;
end;
$$;
