import sys

with open('Dashboard/public/admin/availability.html', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Add html modal
modal_html = """
    <!-- Specific Times Modal -->
    <div id="specificTimesModal" style="position:fixed; inset:0; background:rgba(0,0,0,0.7); z-index:100; display:none; align-items:center; justify-content:center; padding:20px;">
        <div style="background:var(--c-bg); border:1px solid var(--c-border); border-radius:var(--radius-lg); width:100%; max-width:600px; padding:24px; max-height:90vh; overflow-y:auto;">
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:16px;">
                <h3 style="font-size:1.2rem; font-weight:600;" id="specificTimesModalTitle">Select Times for Date</h3>
                <button onclick="closeSpecificTimesModal()" style="background:none; border:none; color:var(--c-text-muted); font-size:1.2rem; cursor:pointer;"><i class="fas fa-times"></i></button>
            </div>
            
            <p style="color:var(--c-text-muted); font-size:0.9rem; margin-bottom:16px;">
                Selecting custom times for this date will override the default time slots. If you unselect all, it will revert to the default time slots.
            </p>
            
            <div class="time-slots-grid" id="specificTimeSlotsGrid">
                <!-- Generated by JS -->
            </div>
            
            <div class="quick-actions" style="margin-bottom: 24px;">
                <button class="quick-action-btn" onclick="selectSpecificEveningSlots()">Evening (6-9 PM)</button>
                <button class="quick-action-btn" onclick="selectAllSpecificSlots()">Select All</button>
                <button class="quick-action-btn" onclick="clearAllSpecificSlots()">Clear All</button>
            </div>
            
            <div style="display:flex; justify-content:flex-end; gap:12px;">
                <button class="btn btn-secondary" onclick="closeSpecificTimesModal()">Cancel</button>
                <button class="btn btn-primary" onclick="saveSpecificTimesModal()">Save specific times</button>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>"""

content = content.replace('<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>', modal_html)

# 2. State
state_str = """        let selectedDates = []; // Specific dates in YYYY-MM-DD format
        let specificDateTimes = {}; // Custom times for specific dates
        let activeModalDate = null;
        let activeModalTimes = [];"""
content = content.replace('        let selectedDates = []; // Specific dates in YYYY-MM-DD format', state_str)

# 3. renderSelectedDatesList modification
old_render_dates = """            list.innerHTML = selectedDates.map(dateStr => {
                const date = new Date(dateStr + 'T00:00:00');
                const formatted = date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
                return `
                    <div style="display: flex; align-items: center; justify-content: space-between; padding: 8px; background: var(--c-bg-card); border-radius: 6px; margin-bottom: 6px;">
                        <span style="font-size: 0.85rem;">${formatted}</span>
                        <button onclick="removeDate('${dateStr}')" style="background: none; border: none; color: #ef4444; cursor: pointer; padding: 4px;">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                `;
            }).join('');"""

new_render_dates = """            list.innerHTML = selectedDates.map(dateStr => {
                const date = new Date(dateStr + 'T00:00:00');
                const formatted = date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
                const specificTimes = specificDateTimes[dateStr] || [];
                const timesLabel = specificTimes.length > 0 ? `${specificTimes.length} custom times` : 'Default times';
                
                return `
                    <div style="display: flex; flex-direction: column; padding: 8px; background: var(--c-bg-card); border-radius: 6px; margin-bottom: 6px;">
                        <div style="display: flex; align-items: center; justify-content: space-between;">
                            <span style="font-size: 0.85rem; font-weight: 500;">${formatted}</span>
                            <div style="display: flex; gap: 4px;">
                                <button onclick="openSpecificTimesModal('${dateStr}')" style="background: rgba(59, 130, 246, 0.1); border: 1px solid rgba(59, 130, 246, 0.2); color: #3b82f6; cursor: pointer; padding: 4px 8px; border-radius: 4px; font-size: 0.75rem;">
                                    <i class="fas fa-clock"></i> Times
                                </button>
                                <button onclick="removeDate('${dateStr}')" style="background: none; border: none; color: #ef4444; cursor: pointer; padding: 4px;">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>
                        <div style="font-size: 0.75rem; color: var(--c-text-muted); margin-top: 4px;">
                            ${timesLabel}
                        </div>
                    </div>
                `;
            }).join('');"""
content = content.replace(old_render_dates, new_render_dates)

# 4. removeDate modification
old_removeDate = """        function removeDate(dateStr) {
            selectedDates = selectedDates.filter(d => d !== dateStr);
            renderCalendar();"""

new_removeDate = """        function removeDate(dateStr) {
            selectedDates = selectedDates.filter(d => d !== dateStr);
            delete specificDateTimes[dateStr];
            renderCalendar();"""
content = content.replace(old_removeDate, new_removeDate)

# 5. insert specific modal functions
modal_funcs = """        // Specific Times Modal
        function openSpecificTimesModal(dateStr) {
            activeModalDate = dateStr;
            activeModalTimes = [...(specificDateTimes[dateStr] || [])];
            
            const dateObj = new Date(dateStr + 'T00:00:00');
            const formatted = dateObj.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
            document.getElementById('specificTimesModalTitle').textContent = `Custom Times: ${formatted}`;
            
            renderSpecificTimeSlots();
            document.getElementById('specificTimesModal').style.display = 'flex';
        }
        
        function closeSpecificTimesModal() {
            document.getElementById('specificTimesModal').style.display = 'none';
            activeModalDate = null;
            activeModalTimes = [];
        }
        
        function renderSpecificTimeSlots() {
            const grid = document.getElementById('specificTimeSlotsGrid');
            grid.innerHTML = '';

            for (let hour = 9; hour <= 21; hour++) {
                for (let min = 0; min < 60; min += 15) {
                    const time24 = `${hour.toString().padStart(2, '0')}:${min.toString().padStart(2, '0')}`;
                    const time12 = formatTime12(hour, min);

                    const slot = document.createElement('div');
                    slot.className = 'time-slot';
                    if (activeModalTimes.includes(time24)) {
                        slot.classList.add('selected');
                    }
                    slot.dataset.time = time24;
                    slot.textContent = time12;
                    slot.onclick = () => toggleSpecificTimeSlot(slot, time24);
                    grid.appendChild(slot);
                }
            }
        }
        
        function toggleSpecificTimeSlot(el, time) {
            el.classList.toggle('selected');
            if (el.classList.contains('selected')) {
                if (!activeModalTimes.includes(time)) activeModalTimes.push(time);
            } else {
                activeModalTimes = activeModalTimes.filter(t => t !== time);
            }
        }
        
        function selectSpecificEveningSlots() {
            document.querySelectorAll('#specificTimeSlotsGrid .time-slot').forEach(slot => {
                const hour = parseInt(slot.dataset.time.split(':')[0]);
                if (hour >= 18 && hour < 21) {
                    slot.classList.add('selected');
                    if (!activeModalTimes.includes(slot.dataset.time)) {
                        activeModalTimes.push(slot.dataset.time);
                    }
                } else {
                    slot.classList.remove('selected');
                    activeModalTimes = activeModalTimes.filter(t => t !== slot.dataset.time);
                }
            });
        }
        
        function selectAllSpecificSlots() {
            activeModalTimes = [];
            document.querySelectorAll('#specificTimeSlotsGrid .time-slot').forEach(slot => {
                slot.classList.add('selected');
                activeModalTimes.push(slot.dataset.time);
            });
        }
        
        function clearAllSpecificSlots() {
            activeModalTimes = [];
            document.querySelectorAll('#specificTimeSlotsGrid .time-slot').forEach(slot => {
                slot.classList.remove('selected');
            });
        }
        
        function saveSpecificTimesModal() {
            if (activeModalTimes.length > 0) {
                specificDateTimes[activeModalDate] = [...activeModalTimes].sort();
            } else {
                delete specificDateTimes[activeModalDate];
            }
            closeSpecificTimesModal();
            renderSelectedDatesList();
            markUnsaved();
        }

        // Lock status
        function updateLockStatus() {"""

content = content.replace('        // Lock status\n        function updateLockStatus() {', modal_funcs)

# 6. loadSettings
old_loadSettings = """                    // Specific Dates
                    selectedDates = data.available_dates || [];

                    // Slot capacity"""
new_loadSettings = """                    // Specific Dates
                    selectedDates = data.available_dates || [];
                    
                    // Specific Date Times
                    specificDateTimes = data.specific_date_times || {};

                    // Slot capacity"""
content = content.replace(old_loadSettings, new_loadSettings)

# 7. saveSettings
old_saveSettings = """                        available_dates: selectedDates.sort(),
                        time_slots: selectedTimeSlots.sort(),"""
new_saveSettings = """                        available_dates: selectedDates.sort(),
                        specific_date_times: specificDateTimes,
                        time_slots: selectedTimeSlots.sort(),"""
content = content.replace(old_saveSettings, new_saveSettings)

with open('Dashboard/public/admin/availability.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("success")
